version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - docker-compose.env

  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: go run main.go
    ports:
      - 8080:8080
    env_file:
      - docker-compose.env
    depends_on:
      - mysql
    tty: true
    stdin_open: true