version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/db
    env_file:
      - .env.docker-compose

  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: go run cmd/api/main.go
    ports:
      - 8080:8080
    env_file:
      - .env.docker-compose
    depends_on:
      - mysql
    tty: true
    stdin_open: true