@startuml
entity users {
id(PK)
--
username
email
}

entity characters {
id(PK)
--
name
character_rarity_id
power
}

entity user_character {
id(PK)
--
user_id
character_id
# 育成ステータスとかの属性も増やす
}

entity character_rarities {
id(PK)
--
name
rarity
}

users -----{ user_character
characters -----{ user_character
character_rarities -----{ characters

@enduml