name: Production-Deproy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: build and deploy
        # uses: actions/heroku@1.0.0
        # ビルドに失敗する為一時的に下記を使用 https://github.com/actions/heroku/issues/11
        uses: sjdonado/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}